name: hello-chroma
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Latest stable Python version
  - pip
  - jupyter
  - pip:
    - chromadb>=0.4.22
    - pypdf>=3.17.4
    - langchain>=0.1.0
    - openai>=1.12.0
    - numpy>=1.26.0
    - tqdm>=4.66.0
    - sentence-transformers>=5.1.0
    - dotenv>=0.9.9
